name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Test
        run: |
          echo "リポジトリに変更が検出されました！"
          echo ${{ vars.REPOSITORY_URL }}